// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs2IXbLsjHLibX4Cie7uoSbz9XsjECQuM',
    appId: '1:950410544983:web:fc358706310adf4807e012',
    messagingSenderId: '950410544983',
    projectId: 'isfa-d6459',
    authDomain: 'isfa-d6459.firebaseapp.com',
    storageBucket: 'isfa-d6459.appspot.com',
    measurementId: 'G-98YN1L6M2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM3b1L_M942QCMkniCTTXBwlPfieJves8',
    appId: '1:950410544983:android:89ddddccad4df53107e012',
    messagingSenderId: '950410544983',
    projectId: 'isfa-d6459',
    storageBucket: 'isfa-d6459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwFj04qWBd9Ir8Tp0Mu2SvRACzutqNKjI',
    appId: '1:950410544983:ios:59d8bfe8bd23858c07e012',
    messagingSenderId: '950410544983',
    projectId: 'isfa-d6459',
    storageBucket: 'isfa-d6459.appspot.com',
    androidClientId: '950410544983-kkvvq8n3q6d6eu4mq711ucc2jtoq5c94.apps.googleusercontent.com',
    iosClientId: '950410544983-28ualvh6uq92upbma9inam7maqraspjk.apps.googleusercontent.com',
    iosBundleId: 'com.denave.isfa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwFj04qWBd9Ir8Tp0Mu2SvRACzutqNKjI',
    appId: '1:950410544983:ios:9f4c2714606ea7ac07e012',
    messagingSenderId: '950410544983',
    projectId: 'isfa-d6459',
    storageBucket: 'isfa-d6459.appspot.com',
    androidClientId: '950410544983-kkvvq8n3q6d6eu4mq711ucc2jtoq5c94.apps.googleusercontent.com',
    iosBundleId: 'com.example.iDensfa',
  );
}
